global:
  namespace: internet-banking

serviceRegistry:
  enabled: false
  name: service-registry
  replicaCount: 1
  image:
    repository: saroja21/internet-banking-service-registry
    tag: "70"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8761

configServer:
  enabled: false
  name: config-server
  replicaCount: 1
  image:
    repository: saroja21/internet-banking-config-server
    tag: "70"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8888

apiGateway:
  enabled: false
  name: api-gateway
  replicaCount: 2
  image:
    repository: saroja21/internet-banking-api-gateway
    tag: "70"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8080

userService:
  enabled: true
  name: internet-banking-user-service
  replicaCount: 2
  image:
    repository: saroja21/internet-banking-user-service
    tag: "main"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  healthCheck:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    failureThreshold: 10

coreBankingService:
  enabled: true
  name: core-banking-service
  replicaCount: 2
  image:
    repository: saroja21/core-banking-service
    tag: "72"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8092
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  healthCheck:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    failureThreshold: 10

fundTransferService:
  enabled: false
  name: fund-transfer-service
  replicaCount: 2
  image:
    repository: saroja21/internet-banking-fund-transfer-service
    tag: "70"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8083

utilityPaymentService:
  enabled: false
  name: utility-payment-service
  replicaCount: 2
  image:
    repository: saroja21/internet-banking-utility-payment-service
    tag: "70"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8084

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
